### PR TITLE
feat: use framework json and optimize view load

### PR DESCRIPTION
**Pull request by devhaozi**
Closes goravel/goravel#273

## 📑 Description

1. Make fiber use framework json. Gin doesn't need this because it use build tag to choose json.
2. Update mock imports to match latest framework update.
3. Only load views when exist.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by devhaozi** [comment]
image

Mock need update.

**Comment by devhaozi** [comment]
PR: goravel/framework#307

**Comment by hwbrzzl** [comment]
CI failed

**Comment by devhaozi** [comment]
> CI failed

Fixed

**Review by hwbrzzl — APPROVED** [review]
LGTM

**Pull request merged**
